FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

# Todo: Remove systemd - only for dev
RUN install_packages dbus systemd

WORKDIR /usr/src
COPY . .
RUN npm install && npm run build

CMD [ "node", "/usr/src/build/index.js" ]
